version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=news
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
    depends_on:
      - mysql
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: 'news'
